from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, UserViewSet, UserRegistrationView

# Create a router instance
router = DefaultRouter()

# 1. Register the ViewSets. This handles all Task CRUD, detail, filtering, 
#    and custom actions (mark-complete/incomplete) under /api/tasks/.
router.register(r'tasks', TaskViewSet, basename='task')

# 2. Register the User ViewSet (Admin only)
router.register(r'users', UserViewSet, basename='user')

# Define urlpatterns
urlpatterns = [
    # 1. User Registration endpoint (Accessible by anyone)
    # This path is defined manually because it uses a simple generic view (CreateAPIView).
    path('users/register/', UserRegistrationView.as_view(), name='user-register'),
    
    # 2. Include all routes generated by the DefaultRouter (tasks and users).
    # This replaces the four problematic manual path definitions.
    path('', include(router.urls)),
]
